version: '3.6'
name: ts-api
services:
  ts-api:
    image: ts-api
    container_name: ts-api
    restart: always
    ports:
      - 9000:80
    env_file:
      - .env.docker
    environment:
      - PORT=80
